#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Vinícius Aires Barros

# Short bio or description (displayed in the header)
description: Computer Scientist passionate about technology

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: viniciusaires

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://viniciusaires.dev

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: html
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

permalink: /:title/

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-gist

# Exclude these files from your production _site
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
    - CNAME

compress_html:
  clippings: all
  comments: all
  endings: [p, li, td]
  profile: true
  startings: [head, body]

timelines:
  - background_image: https://viniciusaires.dev/assets/images/timeline_unicamp.png
    range_years: 2020 - Present
    description: Guest Student in Computer Science at the Institute of Computing of the State University of Campinas - IC Unicamp.

  - background_image: https://viniciusaires.dev/assets/images/timeline_eldorado.png
    range_years: 2018 - Present
    description: Software Analyst in Cloud-based projects.

  - background_image: https://viniciusaires.dev/assets/images/timeline_usp.png
    range_years: 2016 - 2019
    description: Master in Computer Science and Computational Mathematics from University of São Paulo - USP.

  - background_image: https://viniciusaires.dev/assets/images/timeline_uft.png
    range_years: 2015 - 2016
    description: Software Engineering Internship at the Computer Laboratory of the Computer Science Graduation - UFT.

  - background_image: https://viniciusaires.dev/assets/images/timeline_bb.png
    range_years: 2014 - 2015
    description: Software Engineering Internship at the Superintendency of Banco do Brasil of the State of Tocantins - Super TO.

  - background_image: https://viniciusaires.dev/assets/images/timeline_uft.png
    range_years: 2012 - 2016
    description: Graduation in Computer Science from the Federal University of Tocantins (UFT).

works: 
  #- background_image: https://viniciusaires.dev/assets/images/motorola_project.png
  #  project_name: Moto Feedback
  #  description: Artificial intelligence application and automatic creation of issues in Jira based on customer`s feedback.

  #- background_image: https://viniciusaires.dev/assets/images/motorola_project.png
  #  project_name: Demo Mode
  #  description: Cloud application to serve advertising campaign data for demonstration application of new Motorola devices.

  - background_image: https://viniciusaires.dev/assets/images/iotdsm_logo.png
    project_name: IoTDSM
    description: Reference architecture for creating interoperable IoT systems.

  - background_image: https://viniciusaires.dev/assets/images/uft_servicos.png
    project_name: UFT Serviços
    description: Android application for opening and tracking UFT service orders.

  - background_image: https://viniciusaires.dev/assets/images/superto.svg
    project_name: Super TO
    description: Banco do Brasil Superintendence Website at Tocantins.
